### ISSUE TITLE
请教一下这个插件的作用

### ISSUE THREAD

**Issue by hugeorange** [BobbyLH/template-extract-plugin#7]
翰子哥，打扰了😀

请教下这个截图插件

我理解这个插件的作用是在项目打包构建时，把所有的css、js资源抽离出来
有个数组 _templateObject 存储数据
在 @hupu/tool 里面的 snapshot 方法，将 jsx 元素先转换成字符串，然后一起拼成html字符串，然后再调接口

---
不知道以上理解对不对？

---

感觉以上步骤搞起来比较繁琐，还得装一个webpack插件，在html里面加标志位

---
我有个想法不知道有没有问题，还请赐教

在调snapshot 方法时，直接把整个html文档拷贝一下，然后把root里面的元素替换成 jsx 转成的dom字符串，然后把整个拷贝的html文档变成字符串提交给后端
下面是代码示例
```ts
import "./styles.css";
import { useState } from "react";
import ReactDOMServer from "react-dom/server";

const shareDom = () => {
  return (
    <div className="a123">
      我是一个孤独的小白兔 哈哈哈吼吼
      <img
        alt="图片"
        width="50px"
        src="https://tpc.googlesyndication.com/simgad/14955214140788978469"
      />
    </div>
  );
};

const url = "https://xxx/poststring2imagebase64";

export default function App() {
  const [ useImg, setuseImg ] = useState("")

  // 生成截图dom
  const goSnapDom = () => {
    const domstr = ReactDOMServer.renderToString(shareDom());
    const docCopy = document.documentElement.cloneNode(true);
    const root = docCopy.querySelector("#root");
    root.innerHTML = domstr;
    const docCopyStr = docCopy.outerHTML;
    // console.log("domstr===>", docCopyStr);
    sendSnap(docCopyStr);
  }

  // 请求截图
  const sendSnap = async(str) => {
    const params = {
      async: false,
      bgTransparency: false,
      env: "prod",
      fullPage: false,
      height: 765,
      html: str,
      quality: 85,
      width: 375
    };
    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json;charset=utf-8"
      },
      body: JSON.stringify(params)
    })

    const json = await response.json();
    console.log('截图返回的json', json)
    const img = json?.data?.image || ""
    setuseImg(img)
  };

  return (
    <div className="App">
      {shareDom()}
      <div>我是截图生成的img图片</div>
      <img alt="" src={useImg}/>
      <h1 onClick={goSnapDom}>去截图</h1>
    </div>
  );
}

```

**Comment by BobbyTalvin** [comment]
> 我理解这个插件的作用是在项目打包构建时，把所有的css、js资源抽离出来
> 有个数组 _templateObject 存储数据
> 在 @hupu/tool 里面的 snapshot 方法，将 jsx 元素先转换成字符串，然后一起拼成html字符串，然后再调接口
> 

基本就是这个思路，这个 webpack 插件做抽取动作，而后把资源都整合在一个 `_get_extract_template_` 方法中，该方法接收dom字符串作为参数，而后返回带有样式的模板。

为什么要这么绕来绕去，不直接在运行时拿到 dom 而后输出的原因在于：对于外链的 css 没办法用现有的 API 获取，当然，你能用 `getComputedStyle ` 获取某个 dom 的应用样式，而后将需要的 dom 样式遍历出来，变成内联或行内样式 —— 但这就需要改造 `snapshot` 方法，增加了调用方的成本。

当然，这个插件有很多不完善的地方，比如没有做到按需抽取 css 内容，而是整体提取 —— 这也是考虑到有些全局样式可能会对最终的截图效果产生影响。

另外，一个能够优化的地方在于模板的定制，需要截图服务支持这项功能；而满足模板的截图，其实只需要数据传递即可。

**Comment by hugeorange** [comment]
> > 我理解这个插件的作用是在项目打包构建时，把所有的css、js资源抽离出来
> > 有个数组 _templateObject 存储数据
> > 在 @hupu/tool 里面的 snapshot 方法，将 jsx 元素先转换成字符串，然后一起拼成html字符串，然后再调接口
> 
> 基本就是这个思路，这个 webpack 插件做抽取动作，而后把资源都整合在一个 `_get_extract_template_` 方法中，该方法接收dom字符串作为参数，而后返回带有样式的模板。
> 
> 为什么要这么绕来绕去，不直接在运行时拿到 dom 而后输出的原因在于：对于外链的 css 没办法用现有的 API 获取，当然，你能用 `getComputedStyle ` 获取某个 dom 的应用样式，而后将需要的 dom 样式遍历出来，变成内联或行内样式 —— 但这就需要改造 `snapshot` 方法，增加了调用方的成本。
> 
> 当然，这个插件有很多不完善的地方，比如没有做到按需抽取 css 内容，而是整体提取 —— 这也是考虑到有些全局样式可能会对最终的截图效果产生影响。
> 
> 另外，一个能够优化的地方在于模板的定制，需要截图服务支持这项功能；而满足模板的截图，其实只需要数据传递即可。

那我这种直接拷贝整个HTML文档，然后把root元素替换的方法可不可取?
```
  // 生成截图dom
  const goSnapDom = () => {
    const domstr = ReactDOMServer.renderToString(shareDom());
    const docCopy = document.documentElement.cloneNode(true);
    const root = docCopy.querySelector("#root");
    root.innerHTML = domstr;
    const docCopyStr = docCopy.outerHTML;
    // console.log("domstr===>", docCopyStr);
    sendSnap(docCopyStr);
  }
```

**Comment by BobbyTalvin** [comment]
> 那我这种直接拷贝整个HTML文档，然后把root元素替换的方法可不可取?
> 
> ```
>   // 生成截图dom
>   const goSnapDom = () => {
>     const domstr = ReactDOMServer.renderToString(shareDom());
>     const docCopy = document.documentElement.cloneNode(true);
>     const root = docCopy.querySelector("#root");
>     root.innerHTML = domstr;
>     const docCopyStr = docCopy.outerHTML;
>     // console.log("domstr===>", docCopyStr);
>     sendSnap(docCopyStr);
>   }
> ```

可行。
但这么做有几个问题：
1. 无法使用 **[Protocol-relative URLs](https://en.wikipedia.org/wiki/URL#Protocol-relative_URLs)** 的外链资源；
2. 外部加载资源过多，导致截图效率降低；
3. 更多的冗余内容；

**Comment by hugeorange** [comment]
> * 外部加载资源过多，导致截图效率降低；

👍👍👍
